variable "resource_group_location" {
  description = "Location of the resource group"
  default = "Australia East"
}

variable "resource_group_name_prefix" {
    default = "rg"
    description = "Prefix of resource group"
}

variable "generated_key_name" {
  type        = string
  default     = "my-key-pair"
  description = "Key-pair generated by Terraform"
}
